// =====================================================
// LA CUEVA DEL LOBIZÓN — DATA.JS
// Datos históricos del equipo (2014-2025)
// =====================================================

const LCDL_DATA = {

  config: {
    nombre: "La Cueva del Lobizón",
    fundacion: 2004,
    debutCompetitivo: 2014,
    colores: ["#1a1a1a", "#8B1C1C", "#FFFFFF"],
    dtActual: "Diego Coitiño",
    temporadaActual: 2026,
    escudoUrl: "https://drive.google.com/uc?export=view&id=1X8rR2g9tCO0XDe9DLmowPBGMIIYP4lkb",
    // Una vez que tengamos el ID de imagen del escudo, reemplazar arriba
  },

  resumenTemporadas: [
    { temporada: 2014, categoria: "MAYORES", divisional: "I", dt: "Martín Valmaggia", pj: 20, pg: 11, pe: 2, pp: 7, pts: 35, gf: 42, gc: 30, rendimiento: 58.3 },
    { temporada: 2015, categoria: "MAYORES", divisional: "I", dt: "Martín Valmaggia", pj: 21, pg: 13, pe: 4, pp: 4, pts: 43, gf: 48, gc: 33, rendimiento: 68.3 },
    { temporada: 2016, categoria: "MAYORES", divisional: "H", dt: "Martín Valmaggia", pj: 22, pg: 6, pe: 6, pp: 10, pts: 24, gf: 37, gc: 42, rendimiento: 36.4 },
    { temporada: 2017, categoria: "MAYORES", divisional: "H", dt: "Andrés Piñeyrúa", pj: 22, pg: 8, pe: 5, pp: 9, pts: 29, gf: 28, gc: 35, rendimiento: 43.9 },
    { temporada: 2018, categoria: "MAYORES", divisional: "H", dt: "Andrés Piñeyrúa", pj: 22, pg: 7, pe: 7, pp: 8, pts: 28, gf: 29, gc: 27, rendimiento: 42.4 },
    { temporada: 2019, categoria: "MAYORES", divisional: "H", dt: "Uberfil González", pj: 21, pg: 13, pe: 1, pp: 7, pts: 40, gf: 50, gc: 33, rendimiento: 63.5 },
    { temporada: 2020, categoria: "MAYORES", divisional: "G", dt: "Uberfil González", pj: 17, pg: 11, pe: 1, pp: 5, pts: 34, gf: 46, gc: 33, rendimiento: 66.7 },
    { temporada: 2021, categoria: "MAYORES", divisional: "G", dt: "Uberfil González", pj: 22, pg: 8, pe: 1, pp: 13, pts: 25, gf: 32, gc: 55, rendimiento: 37.9 },
    { temporada: 2022, categoria: "MAYORES", divisional: "G", dt: "Santiago Bengochea", pj: 18, pg: 8, pe: 4, pp: 6, pts: 28, gf: 30, gc: 24, rendimiento: 51.9 },
    { temporada: 2023, categoria: "MAYORES", divisional: "F", dt: "Santiago Bengochea", pj: 21, pg: 9, pe: 3, pp: 9, pts: 30, gf: 42, gc: 39, rendimiento: 47.6 },
    { temporada: 2024, categoria: "MAYORES", divisional: "F", dt: "Diego Coitiño", pj: 21, pg: 7, pe: 5, pp: 9, pts: 26, gf: 47, gc: 41, rendimiento: 41.3 },
    { temporada: 2025, categoria: "MAYORES", divisional: "F", dt: "Diego Coitiño", pj: 22, pg: 10, pe: 2, pp: 10, pts: 32, gf: 44, gc: 36, rendimiento: 48.5 },
    { temporada: 2025, categoria: "PRESENIOR", divisional: "E2", dt: "Diego Coitiño", pj: 23, pg: 9, pe: 4, pp: 10, pts: 31, gf: 34, gc: 40, rendimiento: 44.9 },
  ],

  goleadoresHistoricos: [
    { carnet: "28805", nombre: "Federico Rosso Campamar", goles: 117, mayores: 109, presenior: 8, pj: 150 },
    { carnet: "23668", nombre: "Mauro Andrés Serra Baltasar", goles: 58, mayores: 54, presenior: 4, pj: 134 },
    { carnet: "47277", nombre: "Renato Germán Moncalvo Villegas", goles: 52, mayores: 52, presenior: 0, pj: 139 },
    { carnet: "26194", nombre: "Alfonso Rosso Campamar", goles: 36, mayores: 34, presenior: 2, pj: 167 },
    { carnet: "58425", nombre: "Gastón García", goles: 33, mayores: 27, presenior: 6, pj: 65 },
    { carnet: "29552", nombre: "Nicolás Leonardo Zabaleta Vignone", goles: 17, mayores: 16, presenior: 1, pj: 132 },
    { carnet: "27061", nombre: "Federico Andrés Rovascio Caballero", goles: 13, mayores: 13, presenior: 0, pj: 153 },
    { carnet: "23055", nombre: "Agustín Tosar Rovira", goles: 10, mayores: 10, presenior: 0, pj: 66 },
    { carnet: "45626", nombre: "Diego Marcelo Vázquez Pereda", goles: 9, mayores: 9, presenior: 0, pj: 83 },
    { carnet: "32033", nombre: "Enrique Martínez Marchese", goles: 19, mayores: 19, presenior: 0, pj: 190 },
    { carnet: "49830", nombre: "Pablo Rodríguez Cantarelli", goles: 7, mayores: 7, presenior: 0, pj: 64 },
    { carnet: "42159", nombre: "Sigfrido Vettorazzi", goles: 8, mayores: 8, presenior: 0, pj: 184 },
  ],

  jugadores: [
    { carnet: "22726", nombre: "Juan Andrés Aldecoa Villar", pj: 228, pjMayores: 208, pjPresenior: 20, goles: 2, activo: true },
    { carnet: "32033", nombre: "Enrique Martínez Marchese", pj: 190, pjMayores: 174, pjPresenior: 16, goles: 19, activo: true },
    { carnet: "42159", nombre: "Sigfrido Vettorazzi", pj: 184, pjMayores: 162, pjPresenior: 22, goles: 8, activo: true },
    { carnet: "26194", nombre: "Alfonso Rosso Campamar", pj: 167, pjMayores: 146, pjPresenior: 21, goles: 36, activo: true },
    { carnet: "27061", nombre: "Federico Andrés Rovascio Caballero", pj: 153, pjMayores: 138, pjPresenior: 15, goles: 13, activo: true },
    { carnet: "28805", nombre: "Federico Rosso Campamar", pj: 150, pjMayores: 136, pjPresenior: 14, goles: 117, activo: true },
    { carnet: "37332", nombre: "Federico Isper Latorre", pj: 145, pjMayores: 137, pjPresenior: 8, goles: 3, activo: true },
    { carnet: "33715", nombre: "Felipe Castro Carracedo", pj: 141, pjMayores: 141, pjPresenior: 0, goles: 4, activo: false },
    { carnet: "47277", nombre: "Renato Germán Moncalvo Villegas", pj: 139, pjMayores: 139, pjPresenior: 0, goles: 52, activo: true },
    { carnet: "23668", nombre: "Mauro Andrés Serra Baltasar", pj: 134, pjMayores: 117, pjPresenior: 17, goles: 58, activo: true },
    { carnet: "29552", nombre: "Nicolás Leonardo Zabaleta Vignone", pj: 132, pjMayores: 117, pjPresenior: 15, goles: 17, activo: true },
    { carnet: "48561", nombre: "Guillermo Gandolfo", pj: 125, pjMayores: 108, pjPresenior: 17, goles: 0, activo: true },
    { carnet: "38809", nombre: "Cristian Bueno Scaglioni", pj: 93, pjMayores: 76, pjPresenior: 17, goles: 0, activo: true },
    { carnet: "47276", nombre: "Andrés Charlo Berger", pj: 92, pjMayores: 92, pjPresenior: 0, goles: 4, activo: false },
    { carnet: "34491", nombre: "Sttefano Abanoni Paccini", pj: 90, pjMayores: 90, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "45626", nombre: "Diego Marcelo Vázquez Pereda", pj: 83, pjMayores: 83, pjPresenior: 0, goles: 9, activo: false },
    { carnet: "29260", nombre: "Leonardo María Dugrós Bauer", pj: 67, pjMayores: 67, pjPresenior: 0, goles: 2, activo: false },
    { carnet: "23055", nombre: "Agustín Tosar Rovira", pj: 66, pjMayores: 59, pjPresenior: 7, goles: 10, activo: true },
    { carnet: "37698", nombre: "Juan Sebastián Rodríguez Vila", pj: 66, pjMayores: 55, pjPresenior: 11, goles: 0, activo: true },
    { carnet: "58425", nombre: "Gastón García", pj: 65, pjMayores: 54, pjPresenior: 11, goles: 33, activo: true },
    { carnet: "33725", nombre: "Juan Oholeguy", pj: 65, pjMayores: 63, pjPresenior: 2, goles: 2, activo: true },
    { carnet: "49830", nombre: "Pablo Rodríguez Cantarelli", pj: 64, pjMayores: 64, pjPresenior: 0, goles: 7, activo: false },
    { carnet: "49831", nombre: "Andy Besson", pj: 64, pjMayores: 64, pjPresenior: 0, goles: 1, activo: true },
    { carnet: "47158", nombre: "Alexis Matías Suhr Vico", pj: 63, pjMayores: 63, pjPresenior: 0, goles: 3, activo: false },
    { carnet: "30062", nombre: "Michael Macrino D'Ottone", pj: 59, pjMayores: 59, pjPresenior: 0, goles: 3, activo: false },
    { carnet: "55512", nombre: "Marcio Serra", pj: 38, pjMayores: 15, pjPresenior: 23, goles: 2, activo: true },
    { carnet: "61234", nombre: "Gastón Griego", pj: 12, pjMayores: 12, pjPresenior: 0, goles: 2, activo: true },
    { carnet: "60123", nombre: "Rodrigo Kahrs", pj: 30, pjMayores: 23, pjPresenior: 7, goles: 17, activo: true },
    { carnet: "57821", nombre: "Agustín Laventure", pj: 43, pjMayores: 38, pjPresenior: 5, goles: 2, activo: true },
    { carnet: "57822", nombre: "Rodrigo Fernández", pj: 34, pjMayores: 34, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "57823", nombre: "Matías Muriguenez", pj: 31, pjMayores: 31, pjPresenior: 0, goles: 6, activo: true },
    { carnet: "57824", nombre: "Maximiliano Anselmi", pj: 30, pjMayores: 30, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "57825", nombre: "Alex Silva", pj: 27, pjMayores: 27, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "57826", nombre: "Nahuel Rostán", pj: 17, pjMayores: 17, pjPresenior: 0, goles: 1, activo: true },
    { carnet: "60999", nombre: "Santiago Correa", pj: 54, pjMayores: 54, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61000", nombre: "Rodrigo Blanco", pj: 54, pjMayores: 54, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61001", nombre: "Alejandro Perdomo", pj: 55, pjMayores: 55, pjPresenior: 0, goles: 12, activo: true },
    { carnet: "61002", nombre: "Pablo Bernatene", pj: 16, pjMayores: 16, pjPresenior: 0, goles: 2, activo: false },
    { carnet: "61003", nombre: "Fernando Olivera", pj: 16, pjMayores: 16, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61004", nombre: "Luciano Rodríguez", pj: 23, pjMayores: 23, pjPresenior: 0, goles: 2, activo: false },
    { carnet: "61005", nombre: "Carlos Keosseian", pj: 45, pjMayores: 44, pjPresenior: 1, goles: 6, activo: true },
    { carnet: "61006", nombre: "Matías La Cava", pj: 33, pjMayores: 12, pjPresenior: 21, goles: 1, activo: true },
    { carnet: "61007", nombre: "Pablo Farías", pj: 20, pjMayores: 0, pjPresenior: 20, goles: 2, activo: true },
    { carnet: "61008", nombre: "Andrés Piñeyrúa", pj: 13, pjMayores: 0, pjPresenior: 13, goles: 0, activo: true },
    { carnet: "61009", nombre: "Pablo Mayobre", pj: 19, pjMayores: 2, pjPresenior: 17, goles: 1, activo: true },
    { carnet: "61010", nombre: "Leandro Álvarez", pj: 27, pjMayores: 23, pjPresenior: 4, goles: 0, activo: true },
    { carnet: "61011", nombre: "Diego Coitiño", pj: 0, pjMayores: 0, pjPresenior: 0, goles: 0, activo: true }, // solo DT
    { carnet: "61012", nombre: "Agustín Antuña", pj: 17, pjMayores: 17, pjPresenior: 0, goles: 1, activo: true },
    { carnet: "61013", nombre: "Alejandro Antuña", pj: 15, pjMayores: 15, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61014", nombre: "Franco Paulino", pj: 7, pjMayores: 7, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61015", nombre: "Jordan Villoldo", pj: 10, pjMayores: 10, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61016", nombre: "Rodrigo Sasso", pj: 13, pjMayores: 13, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61017", nombre: "Emiliano Cabrera", pj: 10, pjMayores: 10, pjPresenior: 0, goles: 1, activo: true },
    { carnet: "61018", nombre: "Nahuel Ruiz", pj: 10, pjMayores: 10, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61019", nombre: "José Agustín Gonzalvez", pj: 10, pjMayores: 10, pjPresenior: 0, goles: 3, activo: true },
    { carnet: "61020", nombre: "Federico Bastos", pj: 4, pjMayores: 4, pjPresenior: 0, goles: 0, activo: true },
    { carnet: "61021", nombre: "Ezequiel Passarino", pj: 13, pjMayores: 13, pjPresenior: 0, goles: 1, activo: true },
    { carnet: "61022", nombre: "Alexander Acosta", pj: 8, pjMayores: 0, pjPresenior: 8, goles: 0, activo: true },
    { carnet: "61023", nombre: "Agustín Cleffi", pj: 8, pjMayores: 0, pjPresenior: 8, goles: 0, activo: true },
    { carnet: "61024", nombre: "Juan José García", pj: 2, pjMayores: 0, pjPresenior: 2, goles: 0, activo: true },
    { carnet: "61025", nombre: "Diego Benítez", pj: 16, pjMayores: 14, pjPresenior: 2, goles: 5, activo: true },
    { carnet: "61026", nombre: "Nazareno Anselmi", pj: 11, pjMayores: 11, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61027", nombre: "Nahuel González", pj: 6, pjMayores: 6, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61028", nombre: "Rodrigo Pullares", pj: 24, pjMayores: 24, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61029", nombre: "Santiago Borgia", pj: 56, pjMayores: 56, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61030", nombre: "Nicolás Borgia", pj: 28, pjMayores: 28, pjPresenior: 0, goles: 13, activo: false },
    { carnet: "61031", nombre: "Agustín Silvera", pj: 47, pjMayores: 47, pjPresenior: 0, goles: 1, activo: false },
    { carnet: "61032", nombre: "Matías Combe", pj: 13, pjMayores: 13, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61033", nombre: "Diego Marín", pj: 12, pjMayores: 12, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61034", nombre: "Rodrigo Flores", pj: 22, pjMayores: 22, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61035", nombre: "Juan Pablo Braga", pj: 33, pjMayores: 30, pjPresenior: 3, goles: 0, activo: true },
    { carnet: "61036", nombre: "Gabriel Baptista", pj: 8, pjMayores: 8, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61037", nombre: "Martín de Souza", pj: 14, pjMayores: 14, pjPresenior: 0, goles: 2, activo: false },
    { carnet: "61038", nombre: "Andrés Vikonis", pj: 15, pjMayores: 15, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61039", nombre: "Marcio Serra (M)", pj: 15, pjMayores: 15, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61040", nombre: "Santiago Lasa", pj: 18, pjMayores: 18, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61041", nombre: "Martín Crespo", pj: 16, pjMayores: 16, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61042", nombre: "Alejandro Perdomo", pj: 55, pjMayores: 55, pjPresenior: 0, goles: 12, activo: true },
    { carnet: "61043", nombre: "Gerardo Marcelli", pj: 36, pjMayores: 35, pjPresenior: 1, goles: 0, activo: true },
    { carnet: "61044", nombre: "Juan Martín Vargas", pj: 7, pjMayores: 7, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61045", nombre: "Demian Viera", pj: 2, pjMayores: 2, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61046", nombre: "Enzo Rodríguez", pj: 9, pjMayores: 9, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61047", nombre: "Mateo Castro", pj: 14, pjMayores: 14, pjPresenior: 0, goles: 1, activo: false },
    { carnet: "61048", nombre: "Flavio Chagas", pj: 4, pjMayores: 4, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61049", nombre: "Rodrigo Blanco", pj: 54, pjMayores: 54, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61050", nombre: "Gustavo Burchio", pj: 3, pjMayores: 3, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61051", nombre: "Francisco Pou", pj: 15, pjMayores: 15, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61052", nombre: "Facundo Flores", pj: 7, pjMayores: 7, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61053", nombre: "Pablo Flores", pj: 6, pjMayores: 6, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61054", nombre: "Guzmán Infanzón", pj: 6, pjMayores: 6, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61055", nombre: "Martín Etchart", pj: 9, pjMayores: 9, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61056", nombre: "Pablo Caffarelli", pj: 8, pjMayores: 8, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61057", nombre: "Ignacio Diez", pj: 3, pjMayores: 3, pjPresenior: 0, goles: 0, activo: false },
    { carnet: "61058", nombre: "Carlos Keosseian", pj: 45, pjMayores: 44, pjPresenior: 1, goles: 6, activo: true },
    { carnet: "61059", nombre: "Agustín Salagaray", pj: 2, pjMayores: 2, pjPresenior: 0, goles: 0, activo: false },
  ],

  datosCuriosos: [
    { tipo: "record", titulo: "El Goleador", texto: "Federico Rosso es el máximo goleador histórico con 117 goles en 150 partidos. Un promedio de 0.78 goles por partido." },
    { tipo: "record", titulo: "El Eterno Capitán", texto: "Juan Andrés Aldecoa es el jugador con más partidos disputados: 228 en total, el único que superó los 200 partidos." },
    { tipo: "record", titulo: "La Peor Derrota", texto: "El 19/9/2021 sufrimos la derrota más dolorosa: Jean Piaget 12-1. Un partido que nunca se olvida." },
    { tipo: "record", titulo: "La Mejor Temporada", texto: "2015 fue nuestra mejor temporada: 13 victorias, 4 empates y solo 4 derrotas. Promedio de 2.05 puntos por partido." },
    { tipo: "curiosidad", titulo: "Primer Gol Histórico", texto: "El primer gol en la historia de La Cueva fue de Alfonso Rosso Campamar, el 27 de abril de 2014 vs Pallotti Universitario. Perdimos 3-1." },
    { tipo: "curiosidad", titulo: "Primera Victoria", texto: "La primera victoria llegó el 22/6/2014 vs Jean Piaget: 0-1. El gol fue de Agustín Silvera." },
    { tipo: "record", titulo: "Gol de Película", texto: "En 2017 marcamos un gol en el minuto 93 de tiro libre desde media cancha. Datos que hacen historia." },
    { tipo: "curiosidad", titulo: "El Ascenso", texto: "El 6/10/2019 ascendimos a la Divisional G: victoria 2-1 ante Bella Vista. Fue el primer ascenso del club." },
    { tipo: "record", titulo: "Gol 50 de Fede", texto: "El gol número 50 de Federico Rosso llegó el 6/11/2018 vs Arnold Gesell, en una victoria 4-0 donde hizo hat-trick." },
    { tipo: "curiosidad", titulo: "El Arquero Agigantado", texto: "En 2023, Sigfrido Vettorazzi atajó dos penales en la misma jugada vs Macabí Universitario. Un hecho rarísimo." },
    { tipo: "record", titulo: "El Remontada Épica", texto: "En 2024 íbamos 0-4 a los 13 minutos vs NSdL y terminamos empatando 4-4. Renato Moncalvo hizo tres goles." },
    { tipo: "curiosidad", titulo: "Con 9 Jugadores", texto: "En 2025 ganamos 1-0 a Clara Jackson jugando con solo 9 jugadores. Una de las victorias más emotivas." },
    { tipo: "record", titulo: "El Trío Fundador", texto: "Mauro Serra, Enrique Martínez y Juan Aldecoa son los únicos que llevan más de 170 partidos en el club." },
    { tipo: "curiosidad", titulo: "Gol Olímpico Histórico", texto: "Mauro Serra marcó un gol olímpico (directo de corner) vs Estudiantes Españoles en 2019. Fue el último partido de Kike antes de irse a España." },
    { tipo: "record", titulo: "Copa de Plata 2014", texto: "En el primer año de vida, La Cueva ganó la Copa de Plata. La final fue el 4/12/2014 vs C.S.D. Niágara: 2-1 con doblete de Nicolás Borgia." },
    { tipo: "curiosidad", titulo: "Rodrigo Kahrs Imparable", texto: "En 2025, Rodrigo Kahrs marcó 4 goles en una sola tarde: goleada 6-4 vs Mariscal Nasazzi." },
    { tipo: "record", titulo: "El COVID no nos paró", texto: "En 2021 el equipo paró 4 meses por la pandemia y retomó en julio. Aun así disputamos los 22 partidos de la temporada." },
    { tipo: "curiosidad", titulo: "DTs históricos", texto: "Seis directores técnicos han dirigido al equipo: Martín Valmaggia (2014-16), Andrés Piñeyrúa (2017-18), Uberfil González (2019-21), Santiago Bengochea (2022-23) y Diego Coitiño (2024-presente)." },
    { tipo: "record", titulo: "249 partidos y contando", texto: "Al cierre de 2025, La Cueva lleva 249 partidos en Mayores: 111 victorias, 41 empates y 97 derrotas. Rendimiento histórico: 52.6%." },
    { tipo: "curiosidad", titulo: "La Primera Presenior", texto: "En 2025 se incorporó la categoría Pre Senior. El debut fue el 29/3/2025 vs Varela Universitario. Un nuevo capítulo del club." },
    { tipo: "record", titulo: "Goleador en el debut", texto: "Nicolás Borgia fue el primer goleador en una final: Copa de Plata 2014, dos goles de Borgia ante Niágara." },
    { tipo: "curiosidad", titulo: "Federico Rosso x3 penales", texto: "En 2025 (Presenior), Federico Rosso convirtió 3 penales en un solo partido vs Jean Piaget: 5-3." },
  ],

  rivalStats: [
    { rival: "Club Atlético Bella Vista", pj: 13, pg: 7, pe: 1, pp: 5, gf: 25, gc: 22, pts: 22, eficiencia: 56.4 },
    { rival: "Jean Piaget", pj: 12, pg: 7, pe: 1, pp: 4, gf: 18, gc: 28, pts: 22, eficiencia: 61.1 },
    { rival: "Deportivo Mitre", pj: 10, pg: 3, pe: 3, pp: 4, gf: 17, gc: 19, pts: 12, eficiencia: 40.0 },
    { rival: "Clara Jackson Universitario", pj: 8, pg: 5, pe: 2, pp: 1, gf: 15, gc: 12, pts: 17, eficiencia: 70.8 },
    { rival: "La 10 Universitario", pj: 8, pg: 5, pe: 2, pp: 1, gf: 23, gc: 10, pts: 17, eficiencia: 70.8 },
    { rival: "Deportivo Naval", pj: 7, pg: 5, pe: 0, pp: 2, gf: 11, gc: 5, pts: 15, eficiencia: 71.4 },
    { rival: "C.S. y D. Niágara", pj: 7, pg: 4, pe: 1, pp: 2, gf: 11, gc: 10, pts: 13, eficiencia: 61.9 },
    { rival: "Estudiantes Españoles", pj: 7, pg: 3, pe: 3, pp: 1, gf: 17, gc: 12, pts: 12, eficiencia: 57.1 },
    { rival: "Paralamas Universitario", pj: 7, pg: 3, pe: 3, pp: 1, gf: 17, gc: 14, pts: 12, eficiencia: 57.1 },
    { rival: "River Plate Universitario", pj: 7, pg: 2, pe: 4, pp: 1, gf: 19, gc: 17, pts: 10, eficiencia: 47.6 },
    { rival: "Arnold Gesell", pj: 6, pg: 5, pe: 0, pp: 1, gf: 20, gc: 5, pts: 15, eficiencia: 83.3 },
    { rival: "Varela Universitario", pj: 6, pg: 4, pe: 1, pp: 1, gf: 15, gc: 10, pts: 13, eficiencia: 72.2 },
    { rival: "Mariscal Nasazzi", pj: 6, pg: 4, pe: 0, pp: 2, gf: 17, gc: 14, pts: 12, eficiencia: 66.7 },
    { rival: "Veterinaria Universitario", pj: 6, pg: 4, pe: 0, pp: 2, gf: 12, gc: 8, pts: 12, eficiencia: 66.7 },
    { rival: "Familiar Universitario", pj: 3, pg: 3, pe: 0, pp: 0, gf: 8, gc: 4, pts: 9, eficiencia: 100.0 },
    { rival: "Perry Sexta Jrs.", pj: 3, pg: 3, pe: 0, pp: 0, gf: 12, gc: 0, pts: 9, eficiencia: 100.0 },
    { rival: "Poseidón Universitario", pj: 3, pg: 3, pe: 0, pp: 0, gf: 11, gc: 6, pts: 9, eficiencia: 100.0 },
    { rival: "Guichón Universitario", pj: 5, pg: 0, pe: 0, pp: 5, gf: 2, gc: 17, pts: 0, eficiencia: 0.0 },
    { rival: "Gomensoro", pj: 6, pg: 1, pe: 2, pp: 3, gf: 14, gc: 17, pts: 5, eficiencia: 27.8 },
    { rival: "Latino Fútbol Club", pj: 6, pg: 1, pe: 1, pp: 4, gf: 6, gc: 13, pts: 4, eficiencia: 22.2 },
    { rival: "Centro Gallego", pj: 6, pg: 2, pe: 0, pp: 4, gf: 9, gc: 15, pts: 6, eficiencia: 33.3 },
    { rival: "Bella Unión (Univ.)", pj: 6, pg: 2, pe: 0, pp: 4, gf: 8, gc: 12, pts: 6, eficiencia: 33.3 },
    { rival: "América Universitario", pj: 6, pg: 3, pe: 2, pp: 1, gf: 15, gc: 9, pts: 11, eficiencia: 61.1 },
    { rival: "Argos", pj: 6, pg: 3, pe: 1, pp: 2, gf: 11, gc: 9, pts: 10, eficiencia: 55.6 },
    { rival: "Remonte", pj: 6, pg: 1, pe: 1, pp: 4, gf: 10, gc: 14, pts: 4, eficiencia: 22.2 },
    { rival: "Club Estudiantes Ingeniería", pj: 7, pg: 1, pe: 3, pp: 3, gf: 12, gc: 18, pts: 6, eficiencia: 28.6 },
  ],

  goleadoresPorTemporada: {
    2014: [{ nombre: "Federico Rosso", goles: 16 }, { nombre: "Nicolás Borgia", goles: 9 }, { nombre: "Mauro Serra", goles: 4 }],
    2015: [{ nombre: "Mauro Serra", goles: 17 }, { nombre: "Federico Rosso", goles: 11 }, { nombre: "Alfonso Rosso", goles: 7 }],
    2016: [{ nombre: "Federico Rosso", goles: 14 }, { nombre: "Mauro Serra", goles: 5 }, { nombre: "Nicolás Zabaleta", goles: 4 }],
    2017: [{ nombre: "Mauro Serra", goles: 7 }, { nombre: "Agustín Tosar", goles: 4 }, { nombre: "Renato Moncalvo", goles: 5 }],
    2018: [{ nombre: "Mauro Serra", goles: 6 }, { nombre: "Federico Rosso", goles: 6 }, { nombre: "Agustín Tosar", goles: 5 }],
    2019: [{ nombre: "Federico Rosso", goles: 17 }, { nombre: "Nicolás Zabaleta", goles: 5 }, { nombre: "Mauro Serra", goles: 5 }],
    2020: [{ nombre: "Federico Rosso", goles: 20 }, { nombre: "Diego Vázquez", goles: 5 }, { nombre: "Renato Moncalvo", goles: 4 }],
    2021: [{ nombre: "Mauro Serra", goles: 7 }, { nombre: "Pablo Rodríguez", goles: 5 }, { nombre: "Renato Moncalvo", goles: 5 }],
    2022: [{ nombre: "Renato Moncalvo", goles: 9 }, { nombre: "Alfonso Rosso", goles: 5 }, { nombre: "Federico Rosso", goles: 3 }],
    2023: [{ nombre: "Federico Rosso", goles: 15 }, { nombre: "Alfonso Rosso", goles: 9 }, { nombre: "Rodrigo Kahrs", goles: 3 }],
    2024: [{ nombre: "Gastón García", goles: 15 }, { nombre: "Renato Moncalvo", goles: 14 }, { nombre: "Alejandro Perdomo", goles: 4 }],
    2025: [{ nombre: "Renato Moncalvo", goles: 9, categoria: "MAYORES" }, { nombre: "Gastón García", goles: 9, categoria: "MAYORES" }, { nombre: "Rodrigo Kahrs", goles: 8, categoria: "MAYORES" }, { nombre: "Federico Rosso", goles: 8, categoria: "PRESENIOR" }, { nombre: "Gastón García", goles: 6, categoria: "PRESENIOR" }],
  },

};

// API key para el chatbot — reemplazar con la clave real
const CLAUDE_API_KEY = ""; // Se configura en config.js separado

window.LCDL_DATA = LCDL_DATA;
